'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import type { GroceryListResponse } from '../types'

export default function GroceryListPage() {
  const [groceryList, setGroceryList] = useState<GroceryListResponse | null>(null)
  const [checked, setChecked] = useState<Set<string>>(new Set())

  useEffect(() => {
    const stored = sessionStorage.getItem('groceryList')
    if (stored) {
      setGroceryList(JSON.parse(stored))
    }
  }, [])

  function toggleCheck(itemName: string) {
    setChecked(prev => {
      const next = new Set(prev)
      next.has(itemName) ? next.delete(itemName) : next.add(itemName)
      return next
    })
  }

  function handleSendToWhatsApp() {
    if (!groceryList) return
    const lines = groceryList.items
      .map(item => `• ${item.itemName} — ${item.totalPortionInGrams}g`)
      .join('\n')
    const message = `🛒 My Weekly Grocery List:\n\n${lines}\n\nGenerated by Dietary Tracker`
    window.open(`https://wa.me/?text=${encodeURIComponent(message)}`, '_blank')
  }

  if (!groceryList) {
    return (
      <div className="text-center py-20 space-y-4">
        <p className="text-gray-500 text-lg">No grocery list yet.</p>
        <p className="text-gray-400 text-sm">Generate a meal plan first, then click &ldquo;Create Grocery List&rdquo;.</p>
        <Link
          href="/meal-plan"
          className="inline-block mt-4 bg-green-600 hover:bg-green-700 text-white font-semibold px-6 py-2.5 rounded-lg text-sm transition-colors"
        >
          Go to Meal Plan
        </Link>
      </div>
    )
  }

  const uncheckedCount = groceryList.items.length - checked.size

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <h2 className="text-2xl font-bold text-gray-800">Grocery List</h2>
          <p className="text-gray-500 mt-1 text-sm">
            {uncheckedCount} item{uncheckedCount !== 1 ? 's' : ''} remaining · aggregated across your 5-day meal plan
          </p>
        </div>
        <button
          onClick={handleSendToWhatsApp}
          className="flex items-center gap-2 bg-green-500 hover:bg-green-600 text-white font-semibold px-5 py-2.5 rounded-lg text-sm transition-colors"
        >
          <svg className="w-4 h-4" viewBox="0 0 24 24" fill="currentColor">
            <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/>
          </svg>
          Send to WhatsApp
        </button>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        <table className="w-full text-sm">
          <thead>
            <tr className="bg-gray-50 text-gray-500 uppercase text-xs tracking-wide">
              <th className="w-10 px-4 py-3"></th>
              <th className="text-left px-4 py-3">Item</th>
              <th className="text-right px-4 py-3">Total (g)</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {groceryList.items.map((item, i) => {
              const isChecked = checked.has(item.itemName)
              return (
                <tr
                  key={i}
                  onClick={() => toggleCheck(item.itemName)}
                  className={`cursor-pointer transition-colors ${isChecked ? 'bg-gray-50' : i % 2 === 0 ? 'bg-white' : 'bg-gray-50/50'} hover:bg-green-50`}
                >
                  <td className="px-4 py-3 text-center">
                    <input
                      type="checkbox"
                      checked={isChecked}
                      onChange={() => toggleCheck(item.itemName)}
                      onClick={e => e.stopPropagation()}
                      className="w-4 h-4 accent-green-600 cursor-pointer"
                    />
                  </td>
                  <td className={`px-4 py-3 font-medium transition-colors ${isChecked ? 'line-through text-gray-400' : 'text-gray-800'}`}>
                    {item.itemName}
                  </td>
                  <td className={`px-4 py-3 text-right transition-colors ${isChecked ? 'text-gray-400' : 'text-gray-600'}`}>
                    {item.totalPortionInGrams}g
                  </td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>

      <div className="flex justify-between items-center text-sm text-gray-400 pt-1">
        <Link href="/meal-plan" className="hover:text-green-600 transition-colors">
          ← Back to Meal Plan
        </Link>
        {checked.size > 0 && (
          <button
            onClick={() => setChecked(new Set())}
            className="hover:text-red-500 transition-colors"
          >
            Clear all checks
          </button>
        )}
      </div>
    </div>
  )
}
